[project]
name = "collector"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "httpx>=0.28.1",
    "shared",
    "pytest>=8.4.1",
    "typer>=0.27.0",
    "rich>=15.0.0",
]

[tool.uv.sources]
shared = { path = "../shared", editable = true }

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.scripts]
fetch = "collector.commands.fetch:app"
fetch_html = "collector.commands.fetch_html:app"
names = "collector.commands.names:app"
process = "collector.commands.process:app"
fake = "collector.fake:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
